### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by freesunshine0316** [jarfo/kchar#4]
I'm running this code with the tensorflow backend, and encounter the following errors:

[lsong10@bh25fen sub.kchar]$ more train.err 
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    main(params)
  File "train.py", line 24, in main
    model = LSTMCNN(opt)
  File "/gpfs/fs2/scratch/lsong10/exp.full_BoW/sub.kchar/model/LSTMCNN.py", line 95, in LSTMCNN
    cnn = CNN(opt.seq_length, opt.max_word_l, opt.char_vec_size, opt.feature_maps, opt.kernels, chars_embedding)
  File "/gpfs/fs2/scratch/lsong10/exp.full_BoW/sub.kchar/model/LSTMCNN.py", line 63, in CNN
    conv = Convolution2D(feature_map, 1, kernel, activation='tanh', dim_ordering='tf')(x)
  File "/software/python/2.7.12/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/software/python/2.7.12/lib/python2.7/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/software/python/2.7.12/lib/python2.7/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/software/python/2.7.12/lib/python2.7/site-packages/keras/layers/convolutional.py", line 475, in call
    filter_shape=self.W_shape)
  File "/software/python/2.7.12/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2691, in conv2d
    x = tf.nn.conv2d(x, kernel, strides, padding=padding)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 585, in apply_op
    param_name=input_name)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 61, in _SatisfiesTypeCon
straint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType int32 not in list of allowed values: float16, float32, float64

**Comment by jarfo** [comment]
This a keras bug. I have submitted a pull request https://github.com/fchollet/keras/pull/5651
You can manually change the tensorflow_backend.py source code https://github.com/fchollet/keras/pull/5651/files or use the patched file on the patch-1 branch of my keras fork.
