### ISSUE TITLE
Error when running the following command

### ISSUE THREAD

**Issue by prasadii** [jarfo/kchar#6]
For word-level training model, it works
python train.py --savefile word-large --highway_layers 0 --use_chars 0 --use_words 1

But for Char-level training model
python train.py --savefile char-large
The following error is coming...

Traceback (most recent call last):
  File "train.py", line 115, in <module>
    main(params)
  File "train.py", line 37, in main
    model = LSTMCNN(opt)
  File "/home/prasad/tensorflow/kchar3/model/LSTMCNN.py", line 97, in LSTMCNN
    cnn = CNN(opt.seq_length, opt.max_word_l, opt.char_vec_size, opt.feature_maps, opt.kernels, chars_embedding)
  File "/home/prasad/tensorflow/kchar3/model/LSTMCNN.py", line 65, in CNN
    conv = Convolution2D(feature_map, 1, kernel, activation='tanh', dim_ordering='tf')(x)
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/lib64/python2.7/site-packages/keras/layers/convolutional.py", line 475, in call
    filter_shape=self.W_shape)
  File "/usr/lib64/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2691, in conv2d
    x = tf.nn.conv2d(x, kernel, strides, padding=padding)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 585, in apply_op
    param_name=input_name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType int32 not in list of allowed values: float16, float32, float64

Can anyone please give me the solution for this issue and what is the difference between both the training model and which one is giving better prediction ???

**Comment by jarfo** [comment]
I have adapted the code for the new Keras 2 API, and I have checked it with the last github version of Keras.
The character-based language model gives better results.

**Comment by prasadii** [comment]
Thank you...
