### ISSUE TITLE
Running error with train.py

### ISSUE THREAD

**Issue by jingweimo** [jarfo/kchar#7]
I run train.py for a quick check the results, but get the error message:

`one-time setup: preprocessing input train/valid/test files in dir:  data/ptb
Processing text into tensors...
Traceback (most recent call last):

  File "<ipython-input-11-22f0c28a0f81>", line 58, in <module>
    main(params)

  File "<ipython-input-10-53765d159232>", line 2, in main
    loader = BatchLoaderUnk(opt.tokens, opt.data_dir, opt.batch_size, opt.seq_length, opt.max_word_l, opt.n_words, opt.n_chars)

  File "D:\Research\Manuscript\Simplified LSTM\LSTM packages\kchar-master\kchar-master\util\BatchLoaderUnk.py", line 34, in __init__
    self.text_to_tensor(tokens, input_files, vocab_file, tensor_file, char_file, max_word_l)

  File "D:\Research\Manuscript\Simplified LSTM\LSTM packages\kchar-master\kchar-master\util\BatchLoaderUnk.py", line 148, in text_to_tensor
    f = codecs.open(input_files[split], 'r', encoding)

  File "C:\Users\Yuzhen Lu\Anaconda2\lib\codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)

IOError: [Errno 2] No such file or directory: 'data/ptb\\train.txt'`

I use python2.7 (spyder ide) with keras 2.0.5 and theano 0.10

**Comment by jarfo** [comment]
The error seems quite clear: No such file or directory: 'data/ptb\train.txt'You need to execute train.py from the same cloned directory or to use an absolute path for the data dir.RegardsJose


      De: jingweimo <notifications@github.com>
 Para: jarfo/kchar <kchar@noreply.github.com> 
CC: Subscribed <subscribed@noreply.github.com>
 Enviado: Miércoles 21 de junio de 2017 1:57
 Asunto: [jarfo/kchar] Running error with train.py (#7)
   
I run train.py for a quick check the results, but get the error message:`one-time setup: preprocessing input train/valid/test files in dir: data/ptb
Processing text into tensors...
Traceback (most recent call last):File "", line 58, in 
main(params)File "", line 2, in main
loader = BatchLoaderUnk(opt.tokens, opt.data_dir, opt.batch_size, opt.seq_length, opt.max_word_l, opt.n_words, opt.n_chars)File "D:\Research\Manuscript\Simplified LSTM\LSTM packages\kchar-master\kchar-master\util\BatchLoaderUnk.py", line 34, in init
self.text_to_tensor(tokens, input_files, vocab_file, tensor_file, char_file, max_word_l)File "D:\Research\Manuscript\Simplified LSTM\LSTM packages\kchar-master\kchar-master\util\BatchLoaderUnk.py", line 148, in text_to_tensor
f = codecs.open(input_files[split], 'r', encoding)File "C:\Users\Yuzhen Lu\Anaconda2\lib\codecs.py", line 896, in open
file = builtin.open(filename, mode, buffering)IOError: [Errno 2] No such file or directory: 'data/ptb\train.txt'`—

**Comment by jingweimo** [comment]
@jarfo: Thanks! There is no problem with loading the data. The model summary can be printed, but after that, more errors occu:
`ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv2d_gradWeights{convdim=2, border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(20, 15, 35, 21), kshp=(50, 15, 1, 1), filter_dilation=(1, 1)}(InplaceGpuDimShuffle{1,3,0,2}.0, InplaceGpuDimShuffle{0,3,1,2}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1996, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1349, in transform
    new_repl = opt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2752, in local_abstractconv_gw_cudnn
    return local_abstractconv_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2649, in local_abstractconv_cudnn_graph
    if version() < 6000 and op.filter_dilation != (1, 1):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 261, in version
    dnn_available.msg)
RuntimeError: ("We can't determine the cudnn version as it is not available", 'Disabled by dnn.enabled flag')

ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv2d_gradWeights{convdim=2, border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(20, 15, 35, 21), kshp=(50, 15, 1, 1), filter_dilation=(1, 1)}(InplaceGpuDimShuffle{1,3,0,2}.0, InplaceGpuDimShuffle{0,3,1,2}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1996, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1349, in transform
    new_repl = opt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2752, in local_abstractconv_gw_cudnn
    return local_abstractconv_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2649, in local_abstractconv_cudnn_graph
    if version() < 6000 and op.filter_dilation != (1, 1):
  File "C:\Users\Yuzhen Lu\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 261, in version
    dnn_available.msg)
RuntimeError: ("We can't determine the cudnn version as it is not available", 'Disabled by dnn.enabled flag')

ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv2d_gradWeights{convdim=2, border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(20, 15, 35, 21), kshp=(100, 15, 1, 2), filter_dilation=(1, 1)}(InplaceGpuDimShuffle{1,3,0,2}.0, InplaceGpuDimShuffle{0,3,1,2}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1996, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1349, in transform
    new_repl = opt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2752, in local_abstractconv_gw_cudnn
    return local_abstractconv_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2649, in local_abstractconv_cudnn_graph
    if version() < 6000 and op.filter_dilation != (1, 1):
  File "C:\Users\Y L\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 261, in version
    dnn_available.msg)
RuntimeError: ("We can't determine the cudnn version as it is not available", 'Disabled by dnn.enabled flag')

ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv2d_gradWeights{convdim=2, border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(20, 15, 35, 21), kshp=(100, 15, 1, 2), filter_dilation=(1, 1)}(InplaceGpuDimShuffle{1,3,0,2}.0, InplaceGpuDimShuffle{0,3,1,2}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1996, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1349, in transform
    new_repl = opt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2752, in local_abstractconv_gw_cudnn
    return local_abstractconv_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2649, in local_abstractconv_cudnn_graph
    if version() < 6000 and op.filter_dilation != (1, 1):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 261, in version
    dnn_available.msg)
RuntimeError: ("We can't determine the cudnn version as it is not available", 'Disabled by dnn.enabled flag')

ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv2d_gradWeights{convdim=2, border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(20, 15, 35, 21), kshp=(150, 15, 1, 3), filter_dilation=(1, 1)}(InplaceGpuDimShuffle{1,3,0,2}.0, InplaceGpuDimShuffle{0,3,1,2}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1996, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1349, in transform
    new_repl = opt.transform(node)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2752, in local_abstractconv_gw_cudnn
    return local_abstractconv_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 2649, in local_abstractconv_cudnn_graph
    if version() < 6000 and op.filter_dilation != (1, 1):
  File "C:\Users\Y L\\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 261, in version
    dnn_available.msg)
RuntimeError: ("We can't determine the cudnn version as it is not available", 'Disabled by dnn.enabled flag')
...........................................................
    ..........................................................
: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against? On the CPU we do not support float16.
`

I want to know what implementation environment you use. theano version 0.8 or 0.9? OS? cudnn version?
